### ISSUE TITLE
Allow className and style propTypes/defaultProps

### ISSUE THREAD

**Issue by ConAntonakos** [airbnb/react-outside-click-handler#2]
Would it be beneficial to extend `className` and `style` props to root element in render?

Thanks for publishing this!

**Comment by majapw** [comment]
@ConAntonakos we also thought *a lot* about this when we were setting up this repo and eventually landed on the display style being the most important thing for customization. Everything else is likely possible outside of the particular DOM node created by this component.

**Comment by ConAntonakos** [comment]
The one issue that I've bumped into is if you wanted to wrap a CSS-in-JS library (like emotion.js) and style the root component, which in this case would be the `OutsideClickHandler`. I believe you would need a `className` prop to be passed, but I should find a solution that doesn't require dependency on that use case.

Super interesting read, @ljharb. That really helped me understand your viewpoint, and how to potentially manage complexity. I liked the author's approach to the problem, and I'm considering it seriously.

After reading that blog post, I agree with your comment @majapw that `style` would be safest addition.

Thanks for the responses, guys! Closing this.

**Comment by stackoverprof** [comment]
Seems the real experience of the community hated this decision

The article given is gone anyway

**Comment by ljharb** [comment]
The article unfortunately moved; it now lives here: https://medium.com/@JanPaul123/don-t-pass-css-classes-between-components-e9f7ab192785

It’s a better way to author components; whether people like it or not isn’t really relevant, since the goal is to make programs better, not to increase development enjoyment.

**Comment by ahmafi** [comment]
Using tailwind classes and passing them to components, doesn't add this type of complexity that is mentioned in the article, I think. At least, it would be nice if we could have this and add a warning in its documentation that it's a bad practice, instead of not having it at all.

**Comment by ljharb** [comment]
I think it adds precisely that complexity.

Totally fine to link to the article in the docs, though.
