### ISSUE TITLE
How do style the root wrapper div

### ISSUE THREAD

**Issue by audiolion** [airbnb/react-outside-click-handler#21]
> Duplicate of #13; duplicate of #8; duplicate of #2.
> 
> https://brigade.engineering/don-t-pass-css-classes-between-components-e9f7ab192785 is a good read.

Yes I know the article, I get the reasoning, I don't understand how I style that div though. I can use a ref and imperatively change it, but basically the issue I am running into is that I need a height 100% on that div and I dont see a good way to target it with css or make that happen.

**Comment by ljharb** [comment]
```jsx
<div id="root">
  <OutsideClickHandler {...props} />
</div>
```

```css
#root, #root > div {
  height: 100%;
}
```
?

**Comment by audiolion** [comment]
thanks!

**Comment by BrodaNoel** [comment]
`#root, #root > div` is totally unperformant.
Remember that CSS is always evaluated from right to left. Paiting in the browser is going to be slow with no sense.

Using tagNames at the end of a CSS rule, is one of the worst CSS practices
