### ISSUE TITLE
display property should accept "inline" as an option

### ISSUE THREAD

**Issue by nathanmmiller** [airbnb/react-outside-click-handler#27]
"inline-block" is currently accepted but "inline" is not.

**Comment by ljharb** [comment]
What's your use case where you'd want to capture an outside click of an inline element?

**Comment by nathanmmiller** [comment]
Submitted a PR for this. https://github.com/airbnb/react-outside-click-handler/pull/28

Thanks!

**Comment by nathanmmiller** [comment]
> What's your use case where you'd want to capture an outside click of an inline element?

Oh sorry just saw this - the use case is inside a downshift component where renderRow produces an MUI icon and a block with text - if the block is inline, it shows up properly on the same "row" - if it's block it moves itself to the next line, if it's inline-block it doesn't respect the overflow: ellipses property. When wrapping the whole row in an MUI Tooltip component, the usage of this component is great... if it supports that inline block. (If not, the text disappears or overflows the container it's in if set to inline-block.)
