### ISSUE TITLE
Allow Flexbox

### ISSUE THREAD

**Issue by brandonb81** [airbnb/react-outside-click-handler#3]
Would be nice to have `flex` available as one of the display types.

**Comment by ljharb** [comment]
seems reasonable

**Comment by lencioni** [comment]
Why not allow for all possible values of `display`? https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by ljharb** [comment]
That would certainly be the most flexible, but I don't know if we need that level of configurability just yet.

**Comment by brandonb81** [comment]
All of those would seem a bit excessive, but maybe some of the common ones like `table`, `block`, `flex`, `grid` and their `inline` versions as well.

**Comment by erikrahm** [comment]
This issue can be closed as it's been resolved in https://github.com/airbnb/react-outside-click-handler/pull/4 @majapw @ljharb 👍
