### ISSUE TITLE
Support display="contents"

### ISSUE THREAD

**Issue by delijah** [airbnb/react-outside-click-handler#32]
By using `display="contents"` we can avoid having the div, what is generated by `react-outside-click-handler`, having influence on the visual appearance of it's children. This would be of immense value since this lib is only a helper and should not mess with the layout as such.

Proposal: Allow `display` to be set to `contents` OR remove the constraint on the `display`-property completely (it could be of the users choice what value to pass, just mention in the docs what is supported officially).

Some more details about `display="contents"`: http://adrianroselli.com/2018/05/display-contents-is-not-a-css-reset.html

**Comment by ljharb** [comment]
What mode does it fall back to in a browser that doesn’t support this display value?

**Comment by delijah** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/display it should work fine on
- Chrome
- Firefox
- Opera
- Safari
But not on
- IE
- Edge
- Samsung Internet

On IE 11 on Win 7 it falls back to `display="block"`.

Let me know if you need more information?

**Comment by ljharb** [comment]
It seems like we should be able to add contents as a supported value in a semver-minor, then.

**Comment by delijah** [comment]
@ljharb Will you release a new version soon (which includes that fix)?
