### ISSUE TITLE
Cannot provide any CSS classes for the div

### ISSUE THREAD

**Issue by tedeling** [airbnb/react-outside-click-handler#33]
No CSS class(es) can be provided for the div, limiting the actual usage of the div to just the click target.

**Comment by ljharb** [comment]
This is very intentional - see https://github.com/airbnb/react-outside-click-handler/issues/13#issuecomment-423205690 and https://github.com/airbnb/react-outside-click-handler/issues/8#issuecomment-408947995 and https://github.com/airbnb/react-outside-click-handler/issues/2#issuecomment-394891534.
