### ISSUE TITLE
Project does not build on Windows

### ISSUE THREAD

**Issue by marknorrapscm** [airbnb/react-outside-click-handler#42]
I ended up using my Linux VM to get this to build; I got several different errors when trying to build on Windows. This was a week or more ago so I cannot remember exactly what the errors were, but I ran `npm run build` just now so I could get this error:

```
> react-outside-click-handler@1.3.0 build:cjs C:\Work\react-outside-click-handler-forked
> BABEL_ENV=cjs babel src/ -d build/

'BABEL_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-outside-click-handler@1.3.0 build:cjs: `BABEL_ENV=cjs babel src/ -d build/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-outside-click-handler@1.3.0 build:cjs script
```

I don't necessarily mind having to do this in Linux but it is a bit frustrating trying to do it in Windows before realising you'd be better just doing it in a non-Windows environment.

It's worth stating this in the readme.

**Comment by ljharb** [comment]
It hasn't come up before since apparently no Windows devs have tried to contribute before. A PR that uses `cross-env` would be appreciated.
