### ISSUE TITLE
Use with map()

### ISSUE THREAD

**Issue by RobTables** [airbnb/react-outside-click-handler#53]
I have just started using this library to handle outside clicks on popover menus. 

In my case, I have a table where each row has its own popover menu which becomes visible when the row is clicked.

The rows and menus are created using the `map()` method. During each iteration I wrap my popover with the `OutsideClickHandler` component.

For the most part this seems to handle all of my needs but I did notice something I didn't expect but may be normal.

Whenever I click anywhere on the page that is not wrapped, my function for handling outside clicks fires off for each menu created.  Additionally, when clicking on a wrapped element, all other wrapped components will fire off their outside click function.

I would assume this is to be expected but is it also expected (in this case) that a user would add some sort of optimization to avoid those functions firing when their respective menu isn't open/visible?

**Comment by ljharb** [comment]
Typically, thing that aren't visible aren't _rendered_ at all - meaning, since only one popover is visible at a time, only one popover would be _rendered_ at a time, and thus only one OutsideClickHandler.

**Comment by RobTables** [comment]
@ljharb Okay that makes sense. I was originally just hiding and displaying the popover with css based on state but I switched to conditional rendering. Thank you!
