### ISSUE TITLE
Typescript definitions not included?

### ISSUE THREAD

**Issue by Heilemann** [airbnb/react-outside-click-handler#54]
Looks like VSCode is complaining that it can't find the .d.ts file for this.

<img width="523" alt="CleanShot 2022-04-02 at 13 52 23@2x" src="https://user-images.githubusercontent.com/203049/161395225-8edec22f-ebe7-4f51-903e-839ea54aa308.png">

**Comment by ljharb** [comment]
Nope, most packages don't include types, and shouldn't - because that conflates the semver of the types with the semver of the implementation.

The best way for packages to have types is with DefinitelyTyped, and indeed, https://www.npmjs.com/package/@types/react-outside-click-handler exists.
