### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lokeshwarobuli** [airbnb/react-outside-click-handler#58]
Can you please provide TS support ?

**Comment by ljharb** [comment]
What would that mean?

If you want types for the package, the proper place for package types to live is the DefinitelyTyped repo.

**Comment by lokeshwarobuli** [comment]
I tried installing this package using `npm install react-outside-click-handler` and my application is a react typescript application and this error pops up 

![Screenshot 2023-03-07 at 1 20 20 PM](https://user-images.githubusercontent.com/85650351/223514278-226b35d3-a41f-4cfc-b43d-46ae7cc2b3e8.png)

and when I tried installing using the command it popped up, NPM complained stating that it couldn't find the package. Should I manually declare the `.d.ts` in this case ?

**Comment by ljharb** [comment]
Yes, or, you can make a PR to DefinitelyTyped to create those type definitions.

**Comment by lokeshwarobuli** [comment]
Thanks !!

**Comment by ljharb** [comment]
Please tag me on it; i'd be happy to review.
