### ISSUE TITLE
v1.2.1 Release is Broken (build files are missing)

### ISSUE THREAD

**Issue by brianreavis** [airbnb/react-outside-click-handler#6]
The cause: https://github.com/airbnb/react-outside-click-handler/commit/bb56c4f725fd111ab2c79d9bee97224f3cc57e2e

NPM follows what's in .gitignore, unless there's an .npmignore or `"files"` field in package.json. But you probably know that... it's an easy thing to overlook!

cc: @ljharb

**Comment by ljharb** [comment]
Crap, thanks :-) will fix shortly.

**Comment by brianreavis** [comment]
Awesome, thanks @ljharb!

**Comment by ljharb** [comment]
v1.2.2 is published, v1.2.1 is unpublished.
