### ISSUE TITLE
dependency peer issue `airbnb-prop-types` pakage

### ISSUE THREAD

**Issue by jayavel-testsigma** [airbnb/react-outside-click-handler#60]
`npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
npm WARN   node_modules/react-outside-click-handler/node_modules/airbnb-prop-types
npm WARN     airbnb-prop-types@"^2.15.0" from react-outside-click-handler@1.3.0
npm WARN     node_modules/react-outside-click-handler`

**Comment by ljharb** [comment]
That's because this package doesn't support react > 16 yet.

Duplicate of #52.
