### ISSUE TITLE
object.values lib

### ISSUE THREAD

**Issue by jooj123** [airbnb/react-outside-click-handler#7]
Is it possible for me to throw up a PR to remove `object.values` and use the native `Object.values` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values)
to save on bundle size.

I know IE doesn't support it but most consumers have polyfills (in my case babel polyfills with `babel-preset-env`) that already cater for IE

I can add some info to the `README.md` to indicate that you will need to add a polyfill if you want to support IE

**Comment by ljharb** [comment]
If you're concerned with bundle size, you can trivially alias out the `object.values` bundle with `Object.values` itself in your bundler config.

The proper default is the current one - the one that requires the least polyfilling, and requires no additional work by default.

**Comment by jooj123** [comment]
Most react libs out there dont have inbuilt polyfills by default - its better to control that from your app with `babel-preset-env`

Including polyfills by default assumes everyone cares about IE and arcane browsers

**Comment by ljharb** [comment]
For shims, yes (things that self-install). `object.values`, however, doubles as a stand-alone function. And not libs do not in fact rely on polyfills to be present when it’s trivial to use a standalone function.

Everyone should care about older browsers - and the default if *anyone* cares should be the one that breaks for the fewest humans. A slightly larger bundle size is an incredibly minor inconvenience; breaking entirely can make an entire website unusable.

**Comment by romellem** [comment]
But it is fairly trivial to replace the ~20kb library with a simple `for .. in` loop, which has great [browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Browser_compatibility) with none of the heavy weight.

You go from this:

```js
objectValues(DISPLAY))
```

To this:

```js
const DISPLAY_VALUES = [];
for (let display_type in DISPLAY) {
    DISPLAY_VALUES.push(DISPLAY[display_type]);
}
```

For me, that extra 20kb is enough not to use the library flat out, although I'd like to (this works great!).

I'll submit a PR for this, because I think it'd be useful, and doesn't add too much extra code, in my opinion.

**Comment by ljharb** [comment]
@romellem that code is very incorrect, for a number of reasons - not the least of which is that `for..in` iterates over the entire prototype while Object.values only iterates over own properties.

**Comment by romellem** [comment]
Fair enough, but adding a `if (DISPLAY.hasOwnProperty(display_type))` should be enough to fix that.

Based on how this component uses `objectValues(DISPLAY))`, I don't see how using a regular `for .. in` loop to generate that array is any different.

```js
const DISPLAY = {
    BLOCK: 'block',
    FLEX: 'flex',
    INLINE_BLOCK: 'inline-block',
};

propTypes = {
  display: PropTypes.oneOf(objectValues(DISPLAY)),
};

// and

const { display } = this.props;
<div
style={
    display !== DISPLAY.BLOCK && objectValues(DISPLAY).includes(display)
        ? { display }
        : undefined
}
>
```

Should work the same as

```js
const DISPLAY = {
    BLOCK: 'block',
    FLEX: 'flex',
    INLINE_BLOCK: 'inline-block',
};

const DISPLAY_VALUES = [];
for (let display_type in DISPLAY) {
    if (DISPLAY.hasOwnProperty(display_type)) {
        DISPLAY_VALUES.push(DISPLAY[display_type]);
    }
}

propTypes = {
  display: PropTypes.oneOf(objectValues(DISPLAY)),
};

// and

const { display } = this.props;
<div
style={
    display !== DISPLAY.BLOCK && DISPLAY_VALUES.includes(display)
        ? { display }
        : undefined
}
>
```

**Comment by lencioni** [comment]
I know this doesn't solve for everyone using this package, but if you are just looking for an easy way to avoid the object.values package in your project, and you are using something like webpack to bundle your JS, you should be able to use the [`externals` configuration](https://webpack.js.org/configuration/externals/) to swap out that package for something very small.

e.g.

```js
externals: {
  'object.values': 'Object.values',
}
```

**Comment by ljharb** [comment]
@romellem there's edge cases you're not accounting for - like property getters that mutate the object while it's being iterated for values. When you account for them, you end up with identical code as is in the object.values package.

https://github.com/airbnb/react-outside-click-handler/issues/7#issuecomment-413353344 is the best solution when you're in an app that has the appropriate polyfill.

**Comment by romellem** [comment]
@ljharb I think you misunderstood. I wasn't trying to say:

```js
const objectvalues = (obj) => {
  const obj_values = [];
  for (let val in obj) {
    obj_values.push(obj[val]);
  }

  return obj_values;
};
```

Is an appropriate polyfill for the actual `Object.values` method. [Something like this](https://github.com/tc39/proposal-object-values-entries/blob/7c2a54c/polyfill.js) (of which you are the author 😄!) is more robust and covers the edge cases you presented.

I was talking about how in this _specific_ instance `objectValues` is being used within this React component. That is, for prop validation, both in the actual `propTypes` declaration and as a final check when setting our inline `style` on the rendered `<div />`.

I've submitted a PR for this (#10), but if you think the change introduces other issues feel free to reject it.

Thanks for the explanation, and this React component. It is super useful!

**Comment by jooj123** [comment]
Even if i set:
```
externals: {
  'object.values': 'Object.values',
}
```

it doesnt save the cost of all of the bundle size - things like "es-abstract" stick around in bundle for whatever reason (not entirely sure why):

<img width="182" alt="screen shot 2018-08-22 at 11 10 11 pm" src="https://user-images.githubusercontent.com/1309297/44465278-77b19c80-a660-11e8-87d9-4f0180257c71.png">

https://bundlephobia.com/result?p=object.values@1.0.4 
26.7 kB (MINIFIED) seems pretty extreme for something that most modern browsers support (and in my case im forced to add to bundle unnecessarily when I already have the polyfill via `babel-preset-env` settings)

**Comment by ljharb** [comment]
@jooj123 if es-abstract is still in the bundle, then something else presumably depends on it - many things in the es-shims ecosystem use es-abstract.

Minified size isn’t nearly as relevant as gzipped size.

**Comment by lencioni** [comment]
> Minified size isn’t nearly as relevant as gzipped size.

For JavaScript, I disagree with this. While network cost is very important, in my experience most of the cost of JS comes from what happens on the CPU after it is downloaded, especially as [Android phones are getting cheaper and slower over time](https://twitter.com/slightlylate/status/919989184881876992). This more closely correlates to the uncompressed size--especially if you are using newer compression technologies such as brotli.
