### ISSUE TITLE
[Feature] Ability to pass styles to the rendered <div />

### ISSUE THREAD

**Issue by CarsonMcKinstry** [airbnb/react-outside-click-handler#8]
I've run into an issue where I wanted to render this click handler using the styled-components library. Unfortunately, because neither `className` nor `style` are passed through to the <div /> created by the handler, there isn't a lot that you can do in order to style this. 

Is there any plan to add something like this? If not, I'll open a PR shortly with a potential addition.

**Comment by CarsonMcKinstry** [comment]
Please see [PR #9](https://github.com/airbnb/react-outside-click-handler/pull/9)

**Comment by ljharb** [comment]
This is not permitted by design - see https://brigade.engineering/don-t-pass-css-classes-between-components-e9f7ab192785

Duplicate of #2.

**Comment by ivanzusko** [comment]
For those who came here in 2024, and figured out that `https://brigade.engineering` domain is for sale:

https://medium.com/@JanPaul123/don-t-pass-css-classes-between-components-e9f7ab192785
